### ISSUE TITLE
软链发布的问题

### ISSUE THREAD

**Issue by eryajf** [zhenorzz/goploy#10]
简单体验了下软链发布的方式，到目的端之后，每次发布都对应了一个目录，是不是搞错了，理论上应该是同步到版本目录之后，再软链到固定的一个目录里吧。
另外目前的拉取后操作还不是很懂，用mvn报没有这个命令，是构建的时候起了一个独立于系统的bash么？
另外希望能够在文档里给出一些环境变量，诸如Jenkins的 $WORKSPACE 这样的，以便于灵活控制部署。
最后，感谢优秀项目的开源，学习中！

**Comment by zhenorzz** [comment]
看不明白你说的东西，方便加一下群，截图描述清楚吗？
