### ISSUE TITLE
是否考虑支持参数化构建

### ISSUE THREAD

**Issue by xyzjl** [zhenorzz/goploy#101]
类似jenkins的参数化构建机制，但是不用那么复杂，相当于提供自定义环境变量的方式，在每次构建时进行赋值，让脚本编写更灵活，具体建议如下：

1. 在项目配置中，可以添加0个或者多个参数，参数的name作为环境变量允许在后续的脚本中进行使用；参数的value支持字符串和枚举即可
2. 在构建项目时，如果当前项目定义过参数，则弹出参数表单进行填写。如果是字符串类型参数，则直接进行手工输入；如果是枚举类型参数，则提供下拉框进行选择。填写完毕确认后进行构建。

使用场景：
1. 项目支持多平台时，只希望构建某一个平台，可以提高构建速度
2. 项目内有多套配置文件，切换到某一套
3. 项目进行某些临时的构建，或者短期内反复构建并没有代码改动，希望跳过脚本内的测试环节，提高构建速度

**Comment by zhenorzz** [comment]
你的用法都好高级

**Comment by xyzjl** [comment]
哈哈，还好还好

**Comment by zhenorzz** [comment]
这肯定是能支持的，但是没那快。
最近工作比较忙，你先将就用着。
