### ISSUE TITLE
mac start error 

### ISSUE THREAD

**Issue by woxinyoumeng** [zhenorzz/goploy#108]
goroutine 1 [running]:
main.install()
        C:/Users/Administrator/Documents/docker-env/project/go/goploy/cmd/server/main.go:192 +0x43e
main.main()
        C:/Users/Administrator/Documents/docker-env/project/go/goploy/cmd/server/main.go:107 +0xaa

**Comment by zhenorzz** [comment]
line 192, is DB error.
Please check your DB config.

**Comment by zhenorzz** [comment]
if your run on docker, please set those env if needed.
DB_HOST, DB_USER, DB_USER_PASSWORD,DB_NAME,DB_PORT
