### ISSUE TITLE
建议使用运维通道代替ssh-key或增加一个选项的方式

### ISSUE THREAD

**Issue by sjqzhang** [zhenorzz/goploy#11]
ssh-key配置较麻烦，建议使用运维通道代替或增加一个可先项
https://github.com/sjqzhang/ops_channel

**Comment by zhenorzz** [comment]
什么是运维通道

**Comment by sjqzhang** [comment]
类ansible,saltstack，只是更新简单，高效  地址：https://github.com/sjqzhang/ops_channel
