### ISSUE TITLE
希望兼容最新版的 IDE，及相关问题请教

### ISSUE THREAD

**Issue by tlerbao** [zhenorzz/goploy#117]
1. 最新的 2024.X 的 Webstorm 无法搜索到 Goploy 的插件，希望兼容最新版 JB 家 IDE
2. 直接用 root 用户还是新建一个用户比较好，ubuntu 的话默认禁用 root，用 ubuntu 这个用户部署会不会有安全问题。
3. 如果新建一个用户专门用来部署，需要限制执行那些命令呢？`deployuser ALL=(ALL) NOPASSWD: /usr/bin/rsync, /bin/mkdir`
4. 希望增加上传 sshkey 的功能，现在访问仓库只能是以 username:token@github.com.... 形式访问，要给每个仓库设置 token 很麻烦，上传一次，设置项目的时候选一下就行了。

**Comment by zhenorzz** [comment]
1.有空的时候，可以兼容
2.属于你自己研究的范围
3.属于你自己研究的范围
4.仓库应该有一个叫做部署 token 的设置，起码我在 gitlab，github，gitee，gogs 都用过，你可以自己研究一下。
