### ISSUE TITLE
诚恳认真的建议，希望越来越好。

### ISSUE THREAD

**Issue by tlerbao** [zhenorzz/goploy#118]
### 遇到的麻烦

一些文件或目录需要保持生产环境的最新状态（如/upload /runtime .env .database.php），目前的软链部署，会让这些目录和文件回到仓库初始状态。

### 建议

1. 项目设置中增加`公共目录`和`公共文件`设置（数组），在 Doploy 部署项目时，自动在约定俗成的一个目录下新建这些目录和文件，然后实际部署项目相应文件和文件夹软链接到该目录；这样无论怎么部署，这些文件和目录都不会受到影响；即使手动更改了共享目录和共享文件的内容，每次部署的项目引用的也都是最新的。

2. 现在虽然有了软连部署可以存储多个版本，但是好像没有一个非常方便的 Rollback 按钮，可以考虑增加回滚功能。

### 为什么建议？

部署后脚本可以实现，但每个项目都要弄脚本去一一设置显然有些麻烦，而对于后端程序尤其是 Laravel/ThinkPHP 等项目来说这个需求太常见了；如果能在项目设置中简单输入文件名和目录名（如一行一个）那是相当方便了；

**迫切希望作者能够考虑增加此功能，万分感谢，感谢开源。**

### 建议的目录

灵感来自 [Deployer](https://deployer.org/) 这个部署程序我用很久了，就是通过几行配置就实现了，10.5 K的 Star。

Love.com(Project)
  - current ---> 软连到 releases 目录下的 最新版本
  - releases 存储每次部署的版本
    - version-1
      - /app
      - /http
      - ...
      - /upload --- > 软连接到 shared/upload 目录
    - version-2
    - version...
  - shared 
    - /upload 公共目录
    - .env 公共

**Comment by zhenorzz** [comment]
1.自己用脚本实现, 或许软连部署不是你需要的，没必要执着用软连部署。
2.在部署详情那里有 rollback。
或许这个项目真的不是你所需要的，可以看看别的工具，有没有更好。

**Comment by tlerbao** [comment]
> 1.自己用脚本实现, 或许软连部署不是你需要的，没必要执着用软连部署。 2.在部署详情那里有 rollback。 或许这个项目真的不是你所需要的，可以看看别的工具，有没有更好。

好吧，多余了
