### ISSUE TITLE
钉钉通知无效

### ISSUE THREAD

**Issue by rindybo** [zhenorzz/goploy#21]
版本:1.4
通知选择钉钉并填写Webhook地址，构建后无消息推送

**Comment by rindybo** [comment]
日志:
TRACE: 2021/12/08 14:34:24 SyncService.go:42: projectID:1 deploy start
TRACE: 2021/12/08 14:34:24 GitRepo.go:62: projectID:1 git add .
TRACE: 2021/12/08 14:34:24 GitRepo.go:68: projectID:1 git reset --hard
TRACE: 2021/12/08 14:34:24 GitRepo.go:76: projectID:1 git fetch
TRACE: 2021/12/08 14:34:25 GitRepo.go:83: projectID:1 git checkout -B goploy origin/***
TRACE: 2021/12/08 14:34:25 SyncService.go:223: projectID:1npm install
npm run build-test
npm run oss-test
TRACE: 2021/12/08 14:35:48 SyncService.go:275: projectID:1 rsync ****
TRACE: 2021/12/08 14:35:49 SyncService.go:169: projectID:1 deploy success

**Comment by zhenorzz** [comment]
看看自己钉钉的ip白名单或者关键字白名单有没有

**Comment by zhenorzz** [comment]
看看自己钉钉的ip白名单或者关键字白名单有没有

**Comment by rindybo** [comment]
> 看看自己钉钉的ip白名单或者关键字白名单有没有

解决了，谢谢
