### ISSUE TITLE
配置的时候提示这个

### ISSUE THREAD

**Issue by nbnb666888** [zhenorzz/goploy#24]
Start to install the database...
panic: Error 1071: Specified key was too long; max key length is 767 bytes

goroutine 1 [running]:
main.install()
        D:/Users/Administrator/docker-env/project/go/goploy/main.go:226 +0xcdb
main.main()
        D:/Users/Administrator/docker-env/project/go/goploy/main.go:75 +0xd3

**Comment by zhenorzz** [comment]
mysql 版本太低  >5.6 才行
