### ISSUE TITLE
可否在构建后预定义变量加上git相关信息

### ISSUE THREAD

**Issue by teg1c** [zhenorzz/goploy#29]
目前我的项目不需要宿主机做任何事，只需要在目标机上拉取代码，然后执行相关脚本。
但是目标机构建脚本里面我拿不到git的相关信息，比如分支之类的。

**Comment by zhenorzz** [comment]
需要什么，可以列一下。

**Comment by teg1c** [comment]
git 的分支名，commit，作者名

**Comment by zhenorzz** [comment]
好的，择日安排。

**Comment by zhenorzz** [comment]
https://github.com/zhenorzz/goploy/releases/tag/v1.8.1
