### ISSUE TITLE
点击菜单 模板设置  报错 “Error 1054: Unknown column 'insert_time' in 'field list'”

### ISSUE THREAD

**Issue by lorock** [zhenorzz/goploy#3]
点击菜单 模板设置  报错 “Error 1054: Unknown column 'insert_time' in 'field list'”

**Comment by zhenorzz** [comment]
-- DDL修复模板sql漏改
ALTER TABLE `goploy`.`package` 
DROP COLUMN `create_time`,
DROP COLUMN `update_time`,
ADD COLUMN `insert_time` datetime NOT NULL DEFAULT now(),
ADD COLUMN `update_time` datetime NOT NULL DEFAULT now();
