### ISSUE TITLE
部署过程中偶发的会出现报错，但是日志中没有看到报错原因

### ISSUE THREAD

**Issue by zlq1github** [zhenorzz/goploy#35]
部署过程中出现如下报错, 代码有部署到主机上  部署后执行的脚本也有全部执行成功。 部署日志中有效日志只有这一小段 不是必现的报错,只有偶尔会出现这个error
TRACE: 2022/08/08 11:26:39 SyncService.go:314: projectID:51 rsync --exclude goploy-after-pull.sh --include goploy-after-deploy.sh -rtv --exclude .git -e ssh -p 22 -o StrictHostKeyChecking=no -i KEY_FILE --rsync-path=mkdir -p /home/deploy/code/5edfb973-4b39-46ad-9b93-bd6089514ce6 && rsync /opt/goploy/repository/project_51/ deploy@IP:/home/deploy/code/5edfb973-4b39-46ad-9b93-bd6089514ce6
ERROR: 2022/08/08 11:26:42 SyncService.go:425: ssh command err:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M100   112  100    42  100    70     84    140 --:--:-- --:--:-- --:--:--   154^M100   112  100    42  100    70     84    140 --:--:-- --:--:-- --:--:--   154
TRACE: 2022/08/08 11:26:42 SyncService.go:162: projectID:51 deploy fail

**Comment by zhenorzz** [comment]
什么版本，什么系统。

**Comment by zhenorzz** [comment]
看起来像是传输中断。

**Comment by zlq1github** [comment]
解决了,我们这边使用飞书时不能发送消息，自己在构建后脚本中加了一个curl用来处理发布通知 这边返回有问题导致的这个报错
