### ISSUE TITLE
建议增加批量执行脚本的功能

### ISSUE THREAD

**Issue by dnsmap** [zhenorzz/goploy#40]
系统已经有主机SSH KEY，不但可以发布的操作，也可以对一些选定的主机做批量执行脚本，
类似https://github.com/openspug/spug
任务管理--》创建和修改，删除任务（任务里面可以定义脚本和选择需要执行的主机一台或多台，和定时执行），
也可以手动执行任务；
这个里面的批量执行功能，但这系统是py的，不想用，可以考虑下要不要，祝系统越来越好！

**Comment by zhenorzz** [comment]
可以做手动执行
