### ISSUE TITLE
TiDB  Severless Support

### ISSUE THREAD

**Issue by Avey777** [zhenorzz/goploy#50]
错误1105:禁止使用不安全传输的连接。看见https://docs.pingcap.com/tidbcloud/secure-connections-to-serverless-tier-clusters

![image](https://user-images.githubusercontent.com/35259040/225870052-d7c1db12-6c00-4fbd-a753-ceba97d7cd43.png)

**Comment by opcache** [comment]
玩的这么先进吗 ？TiDB Severless 啊。。。
