### ISSUE TITLE
 No known conditions for "./lib/locale/lang/en" entry in "element-plus" package

### ISSUE THREAD

**Issue by baymax55** [zhenorzz/goploy#59]
前端工具是: webstorm
执行 `yarn install` 正常
执行 `yarn build`报错,如下

![image](https://github.com/zhenorzz/goploy/assets/35788491/5085eaff-2350-424d-b436-488d8c61137c)

**Comment by zhenorzz** [comment]
你要二开吗？
不是二开的话，可以直接用release

**Comment by baymax55** [comment]
> 你要二开吗？ 不是二开的话，可以直接用release

我是想让它运行起来找个简单点项目练手下go,算是二开

**Comment by jeeinn** [comment]
如果你只是想让项目跑起来可以用开发模式
`yarn dev`

**Comment by zhenorzz** [comment]
yarn dev试试
我的node 是16的，不知道有没有影响。
如果不行的话，我建议你问问element-plus

**Comment by zhenorzz** [comment]
这个问题我知道了，element版本问题，高版本不在./lib/locale/lang/en，而是在./dist/locale/en
goploy\web\src\lang\index.ts
替换为
import elementEnLocale from 'element-plus/dist/locale/en' // element-ui lang
import elementZhLocale from 'element-plus/dist/locale/zh-cn'
