### ISSUE TITLE
使用两天,一些使用建议

### ISSUE THREAD

**Issue by lizhian** [zhenorzz/goploy#61]
试用了两天,总体感觉还是非常好用的,结合个人的项目情况和使用习惯,提供几个建议

1  PROJECT_NAME 我理解相当于项目编码,一般是英文,但是少了中文字段,希望增加一个PROJECT_Description或者PROJECT_label,存储中文字段,方便测试人员或者其他非开发人员使用这个系统

2 目前在部署路径和传输选项没办法使用预定义变量,希望增加支持,例如
部署路径 :  /opt/goploy-project/${PROJECT_NAME}
传输选项:  -rtv --include ${PROJECT_NAME}.jar

3希望在预定义变量里面增加部署环境变量,更方便编写统一的部署脚本,例如
./project-start --env=${PROJECT_ENV}
PROJECT_ENV=prod(生产环境)   prod-pre(预生产环境)    test(测试环境)    dev(开发环境)  

4 内置的四套环境大部分情况下够用了,但是有些情况还是不够用,希望有自定义部署环境的功能

**Comment by lizhian** [comment]
针对第4点,还可以增加自定义的环境变量,方便不同环境下,使用不同的基础变量
*名称:测试  
*编码:test
变量:
NODE_PATH=path_to_node_home
JAVA_HOME=path_to_java_home
GO_HOME=path_to_go_home

**Comment by lizhian** [comment]
第1点不是很迫切需要
234点希望可以好好考虑一下~感谢

**Comment by zhenorzz** [comment]
1.不考虑，你可以把中文英文一起写在name里面。
2.考虑支持
3.下个版本支持
4.有可能支持

**Comment by zhenorzz** [comment]
> 针对第4点,还可以增加自定义的环境变量,方便不同环境下,使用不同的基础变量 *名称:测试 *编码:test 变量: NODE_PATH=path_to_node_home JAVA_HOME=path_to_java_home GO_HOME=path_to_go_home

这些用你自己的环境变量就好了。

**Comment by zhenorzz** [comment]
4.你可以用${project_label}这个变量,你想定义成什么都行。
