### ISSUE TITLE
关于系统使用总结

### ISSUE THREAD

**Issue by xinjiayu** [zhenorzz/goploy#63]
经过部署使用，发现的问题总结如下：

1. 登录没有验证码，安全性差，别人可以暴力破解
2. 项目设置-》基本配置，传输方式为定制时候，不支持多行多命令，选择sftp或者rsync一样的问题
3. 部署后运行脚本的日志缺失
4. 部署后运行失败也显示成功
5. 无论是部署后运行脚本还是部署完成后运行脚本，需要在目标机器生成，而不是在构建机器时候生成，这样如果遇到自己定制传输方式的时候，就会漏掉文件导致打包失败

**Comment by zhenorzz** [comment]
1.不要放外网，普通验证码我也能破解，需要的话你的自己接短信最好。
2.不支持多行，你可以 &&
3.日志缺失不理解是缺失什么日志。
4.运行失败的标志应该是 exit status，不是stderr
5.在目标机器生产不太方便，详情你可以看看代码，看看有没有可以改进的东西，目前来说，配合传输，把脚本传过去最好，自定义的传输方式，有个变量可以把脚本传过去。
