### ISSUE TITLE
支持k8s部署吗？

### ISSUE THREAD

**Issue by kcxg** [zhenorzz/goploy#66]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhenorzz** [comment]
https://hub.docker.com/repository/docker/zhenorzz/goploy/general

**Comment by zhenorzz** [comment]
需要数据卷持久化

**Comment by kcxg** [comment]
发布应用到 k8s呢

**Comment by zhenorzz** [comment]
可以，写命令就行，支持执行脚本。
