### ISSUE TITLE
项目-传输选项

### ISSUE THREAD

**Issue by hccw** [zhenorzz/goploy#68]
传输方式： sftp
传输选项：pull  -r ${REPOSITORY_PATH}/Apis/bin/Debug/ ${PROJECT_PATH}
问题：
配置的 源文件夹：${REPOSITORY_PATH}/Apis/bin/Debug/
详情中 传输信息中的是 ${REPOSITORY_PATH}/Apis/bin/Debug/
但实际 传的是 ${REPOSITORY_PATH} 整个文件夹

谢谢您的分享~

**Comment by zhenorzz** [comment]
截个图看看，这样有点抽象。

**Comment by hccw** [comment]
配置的 源文件夹：${REPOSITORY_PATH}/Apis/
![1699234800807](https://github.com/zhenorzz/goploy/assets/32183939/16a4811d-c6da-4ea0-a95c-a2b5c3e207d8)

详情中  传输信息中的是 ${REPOSITORY_PATH}/Apis/
![1699234779768](https://github.com/zhenorzz/goploy/assets/32183939/d117d001-a617-4a86-b05b-5874da1f0ce5)

但实际 传的是 ${REPOSITORY_PATH} 整个文件夹
![1699234884872](https://github.com/zhenorzz/goploy/assets/32183939/d32c38d8-393a-49d7-9b81-e89fb80d2562)

按照详情，最后同步到发布服务器上应该只有 Apis 文件夹,但实际是整个项目；文档中也写是会自动拼接 源地址/目的地，我希望是能指定 源地址

**Comment by hccw** [comment]
配置的 源文件夹：${REPOSITORY_PATH}/Apis/
![1699234800807](https://github.com/zhenorzz/goploy/assets/32183939/32c34afe-2a5c-4bd4-8a8c-68a52b192388)
详情中 传输信息中的是 ${REPOSITORY_PATH}/Apis/
1699234779768

但实际 传的是 ${REPOSITORY_PATH} 整个文件夹
1699234884872

按照详情，最后同步到发布服务器上应该只有 Apis 文件夹,但实际是整个项目；文档中也写是会自动拼接 源地址/目的地，我希望是能指定 源地址

**Comment by zhenorzz** [comment]
没支持pull -r 喔。
看看sftp的文档，协议是我自己写的。https://docs.goploy.icu/#/dependency/sftp

**Comment by zhenorzz** [comment]
应该填
--includeRegexp=Apis/
实际还得验证验证。

**Comment by mietl** [comment]
> 应该填 --includeRegexp=Apis/ 实际还得验证验证。

这个问题可以重新打开吗？

我想传输 project_2 下的 dist 文件夹 到服务器的 目的地

目录结构如下
|-- README.md
|-- dist
|   |-- favicon.ico
|   |-- index.html
|-- package-lock.json
|-- package.json
|-- src
|-- ......省略



按照你的回复，我使用这种方式不太行

看过 internal/transmitter/sftp.go 代码必须先有 排除 ，包含才会生效

但即使我这样写 --exclude-regexp=.*   --include-regexp=^dist/.*

他排除了 dist 目录后就不会遍历其子文件, 而我是想将 dist/下的所有文件都上传到远程目录中， 请问有什么办法吗？
