### ISSUE TITLE
你可以自己提交应用到 1Panel-dev/appstore

### ISSUE THREAD

**Issue by Avey777** [zhenorzz/goploy#79]
https://github.com/1Panel-dev/appstore/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E8%87%AA%E5%B7%B1%E6%83%B3%E8%A6%81%E7%9A%84%E5%BA%94%E7%94%A8

等待官方需要太久时间了，我水平有限 。 期待大佬可以提交此应用

**Comment by zhenorzz** [comment]
没问题，学习学习。
