### ISSUE TITLE
对功能上的一点建议

### ISSUE THREAD

**Issue by SPARON** [zhenorzz/goploy#8]
比较看好该项目，目前市面上很多部署工具要么界面很丑，要么配置复杂，要么部署复杂，该项目部署简单，支持一键部署，界面也还可以，不过任何项目都不是完美的，下面给项目提一点建议：

1. 可否添加用户名密码拉去代码功能
2. 将git代码库的ssh key修改为界面配置
3. 支持sqlite嵌入式数据库
4. 可以参考腾讯[蓝盾](https://gitee.com/Tencent-BlueKing/bk-ci)
    - 流水线节点可自定义行为
    - 服务器节点添加，通过安装代理包方式自动添加
    - 模块化/插件化项目功能

**Comment by zhenorzz** [comment]
1.git本来就支持用户名和密码，你链接上带上账号密码就行，google一下；
2.不清楚这个需求你说的是哪里，能加群详细说一下吗；
3.不考虑sqlite，我用了很多mysql的操作；
4.加群细聊；
