### ISSUE TITLE
请问支持url触发构建吗?

### ISSUE THREAD

**Issue by AaronChengHao** [zhenorzz/goploy#85]
作者,您好, 请问goploy支持url触发构建吗?我在管理后台找了一圈也没有找到类似的功能呢, 是没有还是没有发现到.

**Comment by zhenorzz** [comment]
![image](https://github.com/zhenorzz/goploy/assets/28615516/009a672a-d767-40a6-ad5c-18892b2d48ae)
支持git的webhook触发

**Comment by zhenorzz** [comment]
![image](https://github.com/zhenorzz/goploy/assets/28615516/b8724ed3-cec9-4bec-ab64-98985e4f3f30)
或者使用apikey，直接调用接口发布
