### ISSUE TITLE
Invalid request method

### ISSUE THREAD

**Issue by lianyuxue** [zhenorzz/goploy#88]
**Describe the bug**
版本v1.16.1 http://127.0.01:8080/cron/getLogs 调用异常Invalid request method

**To Reproduce**
服务器->定时任务->查看详细定时任务日志

<img width="1270" alt="image" src="https://github.com/zhenorzz/goploy/assets/55083189/aec4ffae-89d0-4448-8cde-2d34d3f5ca44">

**Comment by zhenorzz** [comment]
https://github.com/zhenorzz/goploy/releases/tag/v1.16.2
