### ISSUE TITLE
ssh://git开头的地址测试连接失败，但是实际构建可用

### ISSUE THREAD

**Issue by xyzjl** [zhenorzz/goploy#92]
**问题描述**
`ssh://git@1.2.3.4:22/group/sub_group/project.git`这个形式的git地址点"测试连接"无法连上，但是实际点确认可以保存成功，且后续构建可以正常拉取代码（只是在保存的时候，似乎会再次尝试连接，会有一个"timeout of 5000ms exceeded"的提示）

**环境描述**
git环境: 自建gitlab(14.10.2-ee)
goploy: 1.16.2

**重现步骤**
项目设置->新建项目->输入git地址->测试连接

**Comment by zhenorzz** [comment]
git@1.2.3.4:22/group/sub_group/project.git
直接填这个的话，会怎么样？

**Comment by xyzjl** [comment]
> git@1.2.3.4:22/group/sub_group/project.git 直接填这个的话，会怎么样？

试过了，直接填这个没效果，连不上（用git命令也连不上），因为我的gitlab服务版本自身提供的就是我发的那种形式的链接，这个链接服务器不认

**Comment by zhenorzz** [comment]
这个我研究一下

**Comment by zhenorzz** [comment]
找到问题了，下版本修复。
现在报错不影响你使用。
