### ISSUE TITLE
日志-SFTP日志，time记录时间与实际时间不一致

### ISSUE THREAD

**Issue by lianyuxue** [zhenorzz/goploy#95]
**Describe the bug**
版本v1.16.2 日志-SFTP日志，time记录时间与实际时间不一致
图一为错误
图二为正常

<img width="1271" alt="image" src="https://github.com/zhenorzz/goploy/assets/55083189/5ce337f8-bdb5-4d91-83c3-475779772aae">
<img width="1274" alt="image" src="https://github.com/zhenorzz/goploy/assets/55083189/a9290891-2d1f-4ae4-937a-847b4d552823">

**Comment by zhenorzz** [comment]
看看你数据库是的时区是什么
第一sftp的时间是 CURRENT_TIEMSTAMP, 是数据库自带的
第二个 start time 取值 golang time.Now()
