### ISSUE TITLE
reviewURL 没有 callback 参数

### ISSUE THREAD

**Issue by motuwe** [zhenorzz/goploy#96]
**问题描述**
项目发布审核打开之后，`reviewURL` 没有 `callback` 参数

**环境描述**
 - OS: Goploy Docker 镜像
 - Version: 1.16.1

**Comment by zhenorzz** [comment]
截图看看

**Comment by motuwe** [comment]
![企业微信截图_17114173164594](https://github.com/zhenorzz/goploy/assets/5621857/008c46d9-8cac-4900-88ad-f4271d281703)
![企业微信截图_17114173655035](https://github.com/zhenorzz/goploy/assets/5621857/32edc12b-2e35-4d13-a5f6-f809b5461848)

图一为设置
图二为报错里的地址没有带 callback，前端特意禁用掉了，不知为何？

**Comment by zhenorzz** [comment]
已知问题，下版本修复。
