### ISSUE TITLE
Table 'goploy.monitor' doesn't exist" 

### ISSUE THREAD

**Issue by baymax55** [zhenorzz/goploy#98]
**Describe the bug**
`time="2024-03-26T10:34:53+08:00" level=error msg="get monitor list error, detail:Error 1146: Table 'goploy.monitor' doesn't exist" func="task.monitorTask()" file="monitor.go:63"
`

**To Reproduce**
启动项目后输出该日志,网页可以正常打开

**Screenshots**
![image](https://github.com/zhenorzz/goploy/assets/35788491/b20aa242-938c-4be1-9719-bde8ba29f34f)

**Comment by baymax55** [comment]
注释该task后就好了,请问下该task作用是什么
![image](https://github.com/zhenorzz/goploy/assets/35788491/aa4d906f-856a-47ea-bbc3-e05cdd5a3749)

**Comment by zhenorzz** [comment]
不对，感觉你没装数据库。

**Comment by baymax55** [comment]
已解决,谢谢
